# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'full_keyboard.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QHBoxLayout,
    QLayout, QLineEdit, QSizePolicy, QVBoxLayout,
    QWidget)

from qtpyvcp.widgets.virtual_keyboards.vkb_key import VKBKey
from qtpyvcp.widgets.virtual_keyboards.vkb_modifier_key import VBKModifierKey
import probe_basic_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.setWindowModality(Qt.NonModal)
        Dialog.resize(1450, 500)
        Dialog.setFocusPolicy(Qt.NoFocus)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.vkb_buttons = QFrame(Dialog)
        self.vkb_buttons.setObjectName(u"vkb_buttons")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vkb_buttons.sizePolicy().hasHeightForWidth())
        self.vkb_buttons.setSizePolicy(sizePolicy)
        self.vkb_buttons.setMinimumSize(QSize(1450, 500))
        self.vkb_buttons.setMaximumSize(QSize(1450, 500))
        self.vkb_buttons.setStyleSheet(u"QFrame{\n"
"    border-style: solid;\n"
"    border-width: 4px;\n"
"    border-color: rgb(65, 84, 255);\n"
"    border-radius: 0px;\n"
"    background: rgb(216, 217, 218);\n"
"    font: 20pt \"Probe Basic Bebas Mono\";\n"
"}")
        self.vkb_buttons.setFrameShape(QFrame.StyledPanel)
        self.vkb_buttons.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.vkb_buttons)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(5, 0, 5, -1)
        self.lineEdit = QLineEdit(self.vkb_buttons)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setMinimumSize(QSize(0, 50))
        self.lineEdit.setMaximumSize(QSize(16777215, 50))

        self.verticalLayout_3.addWidget(self.lineEdit)


        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.pushButton_87 = VKBKey(self.vkb_buttons)
        self.pushButton_87.setObjectName(u"pushButton_87")
        sizePolicy.setHeightForWidth(self.pushButton_87.sizePolicy().hasHeightForWidth())
        self.pushButton_87.setSizePolicy(sizePolicy)
        self.pushButton_87.setMinimumSize(QSize(60, 60))
        self.pushButton_87.setMaximumSize(QSize(60, 60))
        font = QFont()
        font.setFamilies([u"Probe Basic Bebas Mono"])
        font.setPointSize(20)
        self.pushButton_87.setFont(font)
        self.pushButton_87.setFocusPolicy(Qt.NoFocus)
        self.pushButton_87.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.pushButton_87)

        self.mk1 = VKBKey(self.vkb_buttons)
        self.mk1.setObjectName(u"mk1")
        sizePolicy.setHeightForWidth(self.mk1.sizePolicy().hasHeightForWidth())
        self.mk1.setSizePolicy(sizePolicy)
        self.mk1.setMinimumSize(QSize(60, 60))
        self.mk1.setMaximumSize(QSize(60, 60))
        self.mk1.setFont(font)
        self.mk1.setFocusPolicy(Qt.NoFocus)
        self.mk1.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk1)

        self.mk2 = VKBKey(self.vkb_buttons)
        self.mk2.setObjectName(u"mk2")
        sizePolicy.setHeightForWidth(self.mk2.sizePolicy().hasHeightForWidth())
        self.mk2.setSizePolicy(sizePolicy)
        self.mk2.setMinimumSize(QSize(60, 60))
        self.mk2.setMaximumSize(QSize(60, 60))
        self.mk2.setFont(font)
        self.mk2.setFocusPolicy(Qt.NoFocus)
        self.mk2.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk2)

        self.mk3 = VKBKey(self.vkb_buttons)
        self.mk3.setObjectName(u"mk3")
        sizePolicy.setHeightForWidth(self.mk3.sizePolicy().hasHeightForWidth())
        self.mk3.setSizePolicy(sizePolicy)
        self.mk3.setMinimumSize(QSize(60, 60))
        self.mk3.setMaximumSize(QSize(60, 60))
        self.mk3.setFont(font)
        self.mk3.setFocusPolicy(Qt.NoFocus)
        self.mk3.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk3)

        self.mk4 = VKBKey(self.vkb_buttons)
        self.mk4.setObjectName(u"mk4")
        sizePolicy.setHeightForWidth(self.mk4.sizePolicy().hasHeightForWidth())
        self.mk4.setSizePolicy(sizePolicy)
        self.mk4.setMinimumSize(QSize(60, 60))
        self.mk4.setMaximumSize(QSize(60, 60))
        self.mk4.setFont(font)
        self.mk4.setFocusPolicy(Qt.NoFocus)
        self.mk4.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk4)

        self.mk5 = VKBKey(self.vkb_buttons)
        self.mk5.setObjectName(u"mk5")
        sizePolicy.setHeightForWidth(self.mk5.sizePolicy().hasHeightForWidth())
        self.mk5.setSizePolicy(sizePolicy)
        self.mk5.setMinimumSize(QSize(60, 60))
        self.mk5.setMaximumSize(QSize(60, 60))
        self.mk5.setFont(font)
        self.mk5.setFocusPolicy(Qt.NoFocus)
        self.mk5.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk5)

        self.mk6 = VKBKey(self.vkb_buttons)
        self.mk6.setObjectName(u"mk6")
        sizePolicy.setHeightForWidth(self.mk6.sizePolicy().hasHeightForWidth())
        self.mk6.setSizePolicy(sizePolicy)
        self.mk6.setMinimumSize(QSize(60, 60))
        self.mk6.setMaximumSize(QSize(60, 60))
        self.mk6.setFont(font)
        self.mk6.setFocusPolicy(Qt.NoFocus)
        self.mk6.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk6)

        self.mk7 = VKBKey(self.vkb_buttons)
        self.mk7.setObjectName(u"mk7")
        sizePolicy.setHeightForWidth(self.mk7.sizePolicy().hasHeightForWidth())
        self.mk7.setSizePolicy(sizePolicy)
        self.mk7.setMinimumSize(QSize(60, 60))
        self.mk7.setMaximumSize(QSize(60, 60))
        self.mk7.setFont(font)
        self.mk7.setFocusPolicy(Qt.NoFocus)
        self.mk7.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk7)

        self.mk8 = VKBKey(self.vkb_buttons)
        self.mk8.setObjectName(u"mk8")
        sizePolicy.setHeightForWidth(self.mk8.sizePolicy().hasHeightForWidth())
        self.mk8.setSizePolicy(sizePolicy)
        self.mk8.setMinimumSize(QSize(60, 60))
        self.mk8.setMaximumSize(QSize(60, 60))
        self.mk8.setFont(font)
        self.mk8.setFocusPolicy(Qt.NoFocus)
        self.mk8.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk8)

        self.mk9 = VKBKey(self.vkb_buttons)
        self.mk9.setObjectName(u"mk9")
        sizePolicy.setHeightForWidth(self.mk9.sizePolicy().hasHeightForWidth())
        self.mk9.setSizePolicy(sizePolicy)
        self.mk9.setMinimumSize(QSize(60, 60))
        self.mk9.setMaximumSize(QSize(60, 60))
        self.mk9.setFont(font)
        self.mk9.setFocusPolicy(Qt.NoFocus)
        self.mk9.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk9)

        self.mk0 = VKBKey(self.vkb_buttons)
        self.mk0.setObjectName(u"mk0")
        sizePolicy.setHeightForWidth(self.mk0.sizePolicy().hasHeightForWidth())
        self.mk0.setSizePolicy(sizePolicy)
        self.mk0.setMinimumSize(QSize(60, 60))
        self.mk0.setMaximumSize(QSize(60, 60))
        self.mk0.setFont(font)
        self.mk0.setFocusPolicy(Qt.NoFocus)
        self.mk0.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.mk0)

        self.dash = VKBKey(self.vkb_buttons)
        self.dash.setObjectName(u"dash")
        sizePolicy.setHeightForWidth(self.dash.sizePolicy().hasHeightForWidth())
        self.dash.setSizePolicy(sizePolicy)
        self.dash.setMinimumSize(QSize(60, 60))
        self.dash.setMaximumSize(QSize(60, 60))
        self.dash.setFont(font)
        self.dash.setFocusPolicy(Qt.NoFocus)
        self.dash.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.dash)

        self.equals = VKBKey(self.vkb_buttons)
        self.equals.setObjectName(u"equals")
        sizePolicy.setHeightForWidth(self.equals.sizePolicy().hasHeightForWidth())
        self.equals.setSizePolicy(sizePolicy)
        self.equals.setMinimumSize(QSize(60, 60))
        self.equals.setMaximumSize(QSize(60, 60))
        self.equals.setFont(font)
        self.equals.setFocusPolicy(Qt.NoFocus)
        self.equals.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.equals)

        self.backspace_2 = VKBKey(self.vkb_buttons)
        self.backspace_2.setObjectName(u"backspace_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.backspace_2.sizePolicy().hasHeightForWidth())
        self.backspace_2.setSizePolicy(sizePolicy1)
        self.backspace_2.setMinimumSize(QSize(0, 60))
        self.backspace_2.setMaximumSize(QSize(16777215, 60))
        self.backspace_2.setFont(font)
        self.backspace_2.setFocusPolicy(Qt.NoFocus)
        self.backspace_2.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.backspace_2)

        self.insert = VKBKey(self.vkb_buttons)
        self.insert.setObjectName(u"insert")
        sizePolicy.setHeightForWidth(self.insert.sizePolicy().hasHeightForWidth())
        self.insert.setSizePolicy(sizePolicy)
        self.insert.setMinimumSize(QSize(60, 60))
        self.insert.setMaximumSize(QSize(60, 60))
        font1 = QFont()
        font1.setFamilies([u"Probe Basic Bebas Mono"])
        font1.setPointSize(13)
        font1.setBold(False)
        font1.setItalic(False)
        self.insert.setFont(font1)
        self.insert.setFocusPolicy(Qt.NoFocus)
        self.insert.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.insert)

        self.np7 = VKBKey(self.vkb_buttons)
        self.np7.setObjectName(u"np7")
        sizePolicy.setHeightForWidth(self.np7.sizePolicy().hasHeightForWidth())
        self.np7.setSizePolicy(sizePolicy)
        self.np7.setMinimumSize(QSize(60, 60))
        self.np7.setMaximumSize(QSize(60, 60))
        font2 = QFont()
        font2.setFamilies([u"Probe Basic Bebas Mono"])
        font2.setPointSize(20)
        font2.setBold(False)
        font2.setItalic(False)
        self.np7.setFont(font2)
        self.np7.setFocusPolicy(Qt.NoFocus)
        self.np7.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.np7)

        self.np8 = VKBKey(self.vkb_buttons)
        self.np8.setObjectName(u"np8")
        sizePolicy.setHeightForWidth(self.np8.sizePolicy().hasHeightForWidth())
        self.np8.setSizePolicy(sizePolicy)
        self.np8.setMinimumSize(QSize(60, 60))
        self.np8.setMaximumSize(QSize(60, 60))
        self.np8.setFont(font2)
        self.np8.setFocusPolicy(Qt.NoFocus)
        self.np8.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.np8)

        self.np9 = VKBKey(self.vkb_buttons)
        self.np9.setObjectName(u"np9")
        sizePolicy.setHeightForWidth(self.np9.sizePolicy().hasHeightForWidth())
        self.np9.setSizePolicy(sizePolicy)
        self.np9.setMinimumSize(QSize(60, 60))
        self.np9.setMaximumSize(QSize(60, 60))
        self.np9.setFont(font2)
        self.np9.setFocusPolicy(Qt.NoFocus)
        self.np9.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.np9)

        self.divide = VKBKey(self.vkb_buttons)
        self.divide.setObjectName(u"divide")
        sizePolicy.setHeightForWidth(self.divide.sizePolicy().hasHeightForWidth())
        self.divide.setSizePolicy(sizePolicy)
        self.divide.setMinimumSize(QSize(60, 60))
        self.divide.setMaximumSize(QSize(60, 60))
        self.divide.setFont(font2)
        self.divide.setFocusPolicy(Qt.NoFocus)
        self.divide.setStyleSheet(u"")

        self.horizontalLayout_8.addWidget(self.divide)


        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.TAB = VKBKey(self.vkb_buttons)
        self.TAB.setObjectName(u"TAB")
        sizePolicy1.setHeightForWidth(self.TAB.sizePolicy().hasHeightForWidth())
        self.TAB.setSizePolicy(sizePolicy1)
        self.TAB.setMinimumSize(QSize(0, 60))
        self.TAB.setMaximumSize(QSize(16777215, 60))
        self.TAB.setFont(font)
        self.TAB.setFocusPolicy(Qt.NoFocus)
        self.TAB.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.TAB)

        self.q = VKBKey(self.vkb_buttons)
        self.q.setObjectName(u"q")
        sizePolicy.setHeightForWidth(self.q.sizePolicy().hasHeightForWidth())
        self.q.setSizePolicy(sizePolicy)
        self.q.setMinimumSize(QSize(60, 60))
        self.q.setMaximumSize(QSize(60, 60))
        self.q.setFont(font)
        self.q.setFocusPolicy(Qt.NoFocus)

        self.horizontalLayout_3.addWidget(self.q)

        self.w = VKBKey(self.vkb_buttons)
        self.w.setObjectName(u"w")
        sizePolicy.setHeightForWidth(self.w.sizePolicy().hasHeightForWidth())
        self.w.setSizePolicy(sizePolicy)
        self.w.setMinimumSize(QSize(60, 60))
        self.w.setMaximumSize(QSize(60, 60))
        self.w.setFont(font)
        self.w.setFocusPolicy(Qt.NoFocus)
        self.w.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.w)

        self.e = VKBKey(self.vkb_buttons)
        self.e.setObjectName(u"e")
        sizePolicy.setHeightForWidth(self.e.sizePolicy().hasHeightForWidth())
        self.e.setSizePolicy(sizePolicy)
        self.e.setMinimumSize(QSize(60, 60))
        self.e.setMaximumSize(QSize(60, 60))
        self.e.setFont(font)
        self.e.setFocusPolicy(Qt.NoFocus)
        self.e.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.e)

        self.r = VKBKey(self.vkb_buttons)
        self.r.setObjectName(u"r")
        sizePolicy.setHeightForWidth(self.r.sizePolicy().hasHeightForWidth())
        self.r.setSizePolicy(sizePolicy)
        self.r.setMinimumSize(QSize(60, 60))
        self.r.setMaximumSize(QSize(60, 60))
        self.r.setFont(font)
        self.r.setFocusPolicy(Qt.NoFocus)
        self.r.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.r)

        self.t = VKBKey(self.vkb_buttons)
        self.t.setObjectName(u"t")
        sizePolicy.setHeightForWidth(self.t.sizePolicy().hasHeightForWidth())
        self.t.setSizePolicy(sizePolicy)
        self.t.setMinimumSize(QSize(60, 60))
        self.t.setMaximumSize(QSize(60, 60))
        self.t.setFont(font)
        self.t.setFocusPolicy(Qt.NoFocus)
        self.t.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.t)

        self.y = VKBKey(self.vkb_buttons)
        self.y.setObjectName(u"y")
        sizePolicy.setHeightForWidth(self.y.sizePolicy().hasHeightForWidth())
        self.y.setSizePolicy(sizePolicy)
        self.y.setMinimumSize(QSize(60, 60))
        self.y.setMaximumSize(QSize(60, 60))
        self.y.setFont(font)
        self.y.setFocusPolicy(Qt.NoFocus)
        self.y.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.y)

        self.u = VKBKey(self.vkb_buttons)
        self.u.setObjectName(u"u")
        sizePolicy.setHeightForWidth(self.u.sizePolicy().hasHeightForWidth())
        self.u.setSizePolicy(sizePolicy)
        self.u.setMinimumSize(QSize(60, 60))
        self.u.setMaximumSize(QSize(60, 60))
        self.u.setFont(font)
        self.u.setFocusPolicy(Qt.NoFocus)
        self.u.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.u)

        self.i = VKBKey(self.vkb_buttons)
        self.i.setObjectName(u"i")
        sizePolicy.setHeightForWidth(self.i.sizePolicy().hasHeightForWidth())
        self.i.setSizePolicy(sizePolicy)
        self.i.setMinimumSize(QSize(60, 60))
        self.i.setMaximumSize(QSize(60, 60))
        self.i.setFont(font)
        self.i.setFocusPolicy(Qt.NoFocus)
        self.i.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.i)

        self.o = VKBKey(self.vkb_buttons)
        self.o.setObjectName(u"o")
        sizePolicy.setHeightForWidth(self.o.sizePolicy().hasHeightForWidth())
        self.o.setSizePolicy(sizePolicy)
        self.o.setMinimumSize(QSize(60, 60))
        self.o.setMaximumSize(QSize(60, 60))
        self.o.setFont(font)
        self.o.setFocusPolicy(Qt.NoFocus)
        self.o.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.o)

        self.p = VKBKey(self.vkb_buttons)
        self.p.setObjectName(u"p")
        sizePolicy.setHeightForWidth(self.p.sizePolicy().hasHeightForWidth())
        self.p.setSizePolicy(sizePolicy)
        self.p.setMinimumSize(QSize(60, 60))
        self.p.setMaximumSize(QSize(60, 60))
        self.p.setFont(font)
        self.p.setFocusPolicy(Qt.NoFocus)
        self.p.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.p)

        self.left_bracket = VKBKey(self.vkb_buttons)
        self.left_bracket.setObjectName(u"left_bracket")
        sizePolicy.setHeightForWidth(self.left_bracket.sizePolicy().hasHeightForWidth())
        self.left_bracket.setSizePolicy(sizePolicy)
        self.left_bracket.setMinimumSize(QSize(60, 60))
        self.left_bracket.setMaximumSize(QSize(60, 60))
        self.left_bracket.setFont(font)
        self.left_bracket.setFocusPolicy(Qt.NoFocus)
        self.left_bracket.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.left_bracket)

        self.right_bracket = VKBKey(self.vkb_buttons)
        self.right_bracket.setObjectName(u"right_bracket")
        sizePolicy.setHeightForWidth(self.right_bracket.sizePolicy().hasHeightForWidth())
        self.right_bracket.setSizePolicy(sizePolicy)
        self.right_bracket.setMinimumSize(QSize(60, 60))
        self.right_bracket.setMaximumSize(QSize(60, 60))
        self.right_bracket.setFont(font)
        self.right_bracket.setFocusPolicy(Qt.NoFocus)
        self.right_bracket.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.right_bracket)

        self.backslash = VKBKey(self.vkb_buttons)
        self.backslash.setObjectName(u"backslash")
        sizePolicy.setHeightForWidth(self.backslash.sizePolicy().hasHeightForWidth())
        self.backslash.setSizePolicy(sizePolicy)
        self.backslash.setMinimumSize(QSize(75, 60))
        self.backslash.setMaximumSize(QSize(70, 60))
        self.backslash.setFont(font)
        self.backslash.setFocusPolicy(Qt.NoFocus)
        self.backslash.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.backslash)

        self.dlt = VKBKey(self.vkb_buttons)
        self.dlt.setObjectName(u"dlt")
        sizePolicy.setHeightForWidth(self.dlt.sizePolicy().hasHeightForWidth())
        self.dlt.setSizePolicy(sizePolicy)
        self.dlt.setMinimumSize(QSize(60, 60))
        self.dlt.setMaximumSize(QSize(60, 60))
        self.dlt.setFont(font1)
        self.dlt.setFocusPolicy(Qt.NoFocus)
        self.dlt.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.dlt)

        self.np4 = VKBKey(self.vkb_buttons)
        self.np4.setObjectName(u"np4")
        sizePolicy.setHeightForWidth(self.np4.sizePolicy().hasHeightForWidth())
        self.np4.setSizePolicy(sizePolicy)
        self.np4.setMinimumSize(QSize(60, 60))
        self.np4.setMaximumSize(QSize(60, 60))
        self.np4.setFont(font2)
        self.np4.setFocusPolicy(Qt.NoFocus)
        self.np4.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.np4)

        self.np5 = VKBKey(self.vkb_buttons)
        self.np5.setObjectName(u"np5")
        sizePolicy.setHeightForWidth(self.np5.sizePolicy().hasHeightForWidth())
        self.np5.setSizePolicy(sizePolicy)
        self.np5.setMinimumSize(QSize(60, 60))
        self.np5.setMaximumSize(QSize(60, 60))
        self.np5.setFont(font2)
        self.np5.setFocusPolicy(Qt.NoFocus)
        self.np5.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.np5)

        self.np6 = VKBKey(self.vkb_buttons)
        self.np6.setObjectName(u"np6")
        sizePolicy.setHeightForWidth(self.np6.sizePolicy().hasHeightForWidth())
        self.np6.setSizePolicy(sizePolicy)
        self.np6.setMinimumSize(QSize(60, 60))
        self.np6.setMaximumSize(QSize(60, 60))
        self.np6.setFont(font2)
        self.np6.setFocusPolicy(Qt.NoFocus)
        self.np6.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.np6)

        self.multiply = VKBKey(self.vkb_buttons)
        self.multiply.setObjectName(u"multiply")
        sizePolicy.setHeightForWidth(self.multiply.sizePolicy().hasHeightForWidth())
        self.multiply.setSizePolicy(sizePolicy)
        self.multiply.setMinimumSize(QSize(60, 60))
        self.multiply.setMaximumSize(QSize(60, 60))
        self.multiply.setFont(font2)
        self.multiply.setFocusPolicy(Qt.NoFocus)
        self.multiply.setStyleSheet(u"")

        self.horizontalLayout_3.addWidget(self.multiply)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.CAPS = VKBKey(self.vkb_buttons)
        self.CAPS.setObjectName(u"CAPS")
        sizePolicy1.setHeightForWidth(self.CAPS.sizePolicy().hasHeightForWidth())
        self.CAPS.setSizePolicy(sizePolicy1)
        self.CAPS.setMinimumSize(QSize(0, 60))
        self.CAPS.setMaximumSize(QSize(16777215, 60))
        self.CAPS.setFont(font)
        self.CAPS.setFocusPolicy(Qt.NoFocus)
        self.CAPS.setStyleSheet(u"")
        self.CAPS.setCheckable(True)

        self.horizontalLayout_4.addWidget(self.CAPS)

        self.a = VKBKey(self.vkb_buttons)
        self.a.setObjectName(u"a")
        sizePolicy.setHeightForWidth(self.a.sizePolicy().hasHeightForWidth())
        self.a.setSizePolicy(sizePolicy)
        self.a.setMinimumSize(QSize(60, 60))
        self.a.setMaximumSize(QSize(60, 60))
        self.a.setFont(font)
        self.a.setFocusPolicy(Qt.NoFocus)
        self.a.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.a)

        self.s = VKBKey(self.vkb_buttons)
        self.s.setObjectName(u"s")
        sizePolicy.setHeightForWidth(self.s.sizePolicy().hasHeightForWidth())
        self.s.setSizePolicy(sizePolicy)
        self.s.setMinimumSize(QSize(60, 60))
        self.s.setMaximumSize(QSize(60, 60))
        self.s.setFont(font)
        self.s.setFocusPolicy(Qt.NoFocus)
        self.s.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.s)

        self.d = VKBKey(self.vkb_buttons)
        self.d.setObjectName(u"d")
        sizePolicy.setHeightForWidth(self.d.sizePolicy().hasHeightForWidth())
        self.d.setSizePolicy(sizePolicy)
        self.d.setMinimumSize(QSize(60, 60))
        self.d.setMaximumSize(QSize(60, 60))
        self.d.setFont(font)
        self.d.setFocusPolicy(Qt.NoFocus)
        self.d.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.d)

        self.f = VKBKey(self.vkb_buttons)
        self.f.setObjectName(u"f")
        sizePolicy.setHeightForWidth(self.f.sizePolicy().hasHeightForWidth())
        self.f.setSizePolicy(sizePolicy)
        self.f.setMinimumSize(QSize(60, 60))
        self.f.setMaximumSize(QSize(60, 60))
        self.f.setFont(font)
        self.f.setFocusPolicy(Qt.NoFocus)
        self.f.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.f)

        self.g = VKBKey(self.vkb_buttons)
        self.g.setObjectName(u"g")
        sizePolicy.setHeightForWidth(self.g.sizePolicy().hasHeightForWidth())
        self.g.setSizePolicy(sizePolicy)
        self.g.setMinimumSize(QSize(60, 60))
        self.g.setMaximumSize(QSize(60, 60))
        self.g.setFont(font)
        self.g.setFocusPolicy(Qt.NoFocus)
        self.g.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.g)

        self.h = VKBKey(self.vkb_buttons)
        self.h.setObjectName(u"h")
        sizePolicy.setHeightForWidth(self.h.sizePolicy().hasHeightForWidth())
        self.h.setSizePolicy(sizePolicy)
        self.h.setMinimumSize(QSize(60, 60))
        self.h.setMaximumSize(QSize(60, 60))
        self.h.setFont(font)
        self.h.setFocusPolicy(Qt.NoFocus)
        self.h.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.h)

        self.j = VKBKey(self.vkb_buttons)
        self.j.setObjectName(u"j")
        sizePolicy.setHeightForWidth(self.j.sizePolicy().hasHeightForWidth())
        self.j.setSizePolicy(sizePolicy)
        self.j.setMinimumSize(QSize(60, 60))
        self.j.setMaximumSize(QSize(60, 60))
        self.j.setFont(font)
        self.j.setFocusPolicy(Qt.NoFocus)
        self.j.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.j)

        self.k = VKBKey(self.vkb_buttons)
        self.k.setObjectName(u"k")
        sizePolicy.setHeightForWidth(self.k.sizePolicy().hasHeightForWidth())
        self.k.setSizePolicy(sizePolicy)
        self.k.setMinimumSize(QSize(60, 60))
        self.k.setMaximumSize(QSize(60, 60))
        self.k.setFont(font)
        self.k.setFocusPolicy(Qt.NoFocus)
        self.k.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.k)

        self.l = VKBKey(self.vkb_buttons)
        self.l.setObjectName(u"l")
        sizePolicy.setHeightForWidth(self.l.sizePolicy().hasHeightForWidth())
        self.l.setSizePolicy(sizePolicy)
        self.l.setMinimumSize(QSize(60, 60))
        self.l.setMaximumSize(QSize(60, 60))
        self.l.setFont(font)
        self.l.setFocusPolicy(Qt.NoFocus)
        self.l.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.l)

        self.semicolon = VKBKey(self.vkb_buttons)
        self.semicolon.setObjectName(u"semicolon")
        sizePolicy.setHeightForWidth(self.semicolon.sizePolicy().hasHeightForWidth())
        self.semicolon.setSizePolicy(sizePolicy)
        self.semicolon.setMinimumSize(QSize(60, 60))
        self.semicolon.setMaximumSize(QSize(60, 60))
        self.semicolon.setFont(font)
        self.semicolon.setFocusPolicy(Qt.NoFocus)
        self.semicolon.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.semicolon)

        self.apostraphe = VKBKey(self.vkb_buttons)
        self.apostraphe.setObjectName(u"apostraphe")
        sizePolicy.setHeightForWidth(self.apostraphe.sizePolicy().hasHeightForWidth())
        self.apostraphe.setSizePolicy(sizePolicy)
        self.apostraphe.setMinimumSize(QSize(60, 60))
        self.apostraphe.setMaximumSize(QSize(60, 60))
        self.apostraphe.setFont(font)
        self.apostraphe.setFocusPolicy(Qt.NoFocus)
        self.apostraphe.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.apostraphe)

        self.enter_2 = VKBKey(self.vkb_buttons)
        self.enter_2.setObjectName(u"enter_2")
        sizePolicy.setHeightForWidth(self.enter_2.sizePolicy().hasHeightForWidth())
        self.enter_2.setSizePolicy(sizePolicy)
        self.enter_2.setMinimumSize(QSize(120, 60))
        self.enter_2.setMaximumSize(QSize(120, 60))
        self.enter_2.setFont(font)
        self.enter_2.setFocusPolicy(Qt.NoFocus)
        self.enter_2.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.enter_2)

        self.home = VKBKey(self.vkb_buttons)
        self.home.setObjectName(u"home")
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        self.home.setMinimumSize(QSize(60, 60))
        self.home.setMaximumSize(QSize(60, 60))
        self.home.setFont(font1)
        self.home.setFocusPolicy(Qt.NoFocus)
        self.home.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.home)

        self.np1 = VKBKey(self.vkb_buttons)
        self.np1.setObjectName(u"np1")
        sizePolicy.setHeightForWidth(self.np1.sizePolicy().hasHeightForWidth())
        self.np1.setSizePolicy(sizePolicy)
        self.np1.setMinimumSize(QSize(60, 60))
        self.np1.setMaximumSize(QSize(60, 60))
        self.np1.setFont(font2)
        self.np1.setFocusPolicy(Qt.NoFocus)
        self.np1.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.np1)

        self.np2 = VKBKey(self.vkb_buttons)
        self.np2.setObjectName(u"np2")
        sizePolicy.setHeightForWidth(self.np2.sizePolicy().hasHeightForWidth())
        self.np2.setSizePolicy(sizePolicy)
        self.np2.setMinimumSize(QSize(60, 60))
        self.np2.setMaximumSize(QSize(60, 60))
        self.np2.setFont(font2)
        self.np2.setFocusPolicy(Qt.NoFocus)
        self.np2.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.np2)

        self.np3 = VKBKey(self.vkb_buttons)
        self.np3.setObjectName(u"np3")
        sizePolicy.setHeightForWidth(self.np3.sizePolicy().hasHeightForWidth())
        self.np3.setSizePolicy(sizePolicy)
        self.np3.setMinimumSize(QSize(60, 60))
        self.np3.setMaximumSize(QSize(60, 60))
        self.np3.setFont(font2)
        self.np3.setFocusPolicy(Qt.NoFocus)
        self.np3.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.np3)

        self.subtract = VKBKey(self.vkb_buttons)
        self.subtract.setObjectName(u"subtract")
        sizePolicy.setHeightForWidth(self.subtract.sizePolicy().hasHeightForWidth())
        self.subtract.setSizePolicy(sizePolicy)
        self.subtract.setMinimumSize(QSize(60, 60))
        self.subtract.setMaximumSize(QSize(60, 60))
        self.subtract.setFont(font2)
        self.subtract.setFocusPolicy(Qt.NoFocus)
        self.subtract.setStyleSheet(u"")

        self.horizontalLayout_4.addWidget(self.subtract)


        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.vbkmodifierkey = VBKModifierKey(self.vkb_buttons)
        self.vbkmodifierkey.setObjectName(u"vbkmodifierkey")
        sizePolicy1.setHeightForWidth(self.vbkmodifierkey.sizePolicy().hasHeightForWidth())
        self.vbkmodifierkey.setSizePolicy(sizePolicy1)
        self.vbkmodifierkey.setMinimumSize(QSize(0, 60))
        self.vbkmodifierkey.setMaximumSize(QSize(16777215, 60))
        font3 = QFont()
        font3.setFamilies([u"Probe Basic Bebas Mono"])
        font3.setPointSize(15)
        self.vbkmodifierkey.setFont(font3)
        self.vbkmodifierkey.setFocusPolicy(Qt.NoFocus)
        self.vbkmodifierkey.setStyleSheet(u"")
        self.vbkmodifierkey.setCheckable(True)

        self.horizontalLayout_5.addWidget(self.vbkmodifierkey)

        self.z = VKBKey(self.vkb_buttons)
        self.z.setObjectName(u"z")
        sizePolicy.setHeightForWidth(self.z.sizePolicy().hasHeightForWidth())
        self.z.setSizePolicy(sizePolicy)
        self.z.setMinimumSize(QSize(60, 60))
        self.z.setMaximumSize(QSize(60, 60))
        self.z.setFont(font)
        self.z.setFocusPolicy(Qt.NoFocus)
        self.z.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.z)

        self.x = VKBKey(self.vkb_buttons)
        self.x.setObjectName(u"x")
        sizePolicy.setHeightForWidth(self.x.sizePolicy().hasHeightForWidth())
        self.x.setSizePolicy(sizePolicy)
        self.x.setMinimumSize(QSize(60, 60))
        self.x.setMaximumSize(QSize(60, 60))
        self.x.setFont(font)
        self.x.setFocusPolicy(Qt.NoFocus)
        self.x.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.x)

        self.c = VKBKey(self.vkb_buttons)
        self.c.setObjectName(u"c")
        sizePolicy.setHeightForWidth(self.c.sizePolicy().hasHeightForWidth())
        self.c.setSizePolicy(sizePolicy)
        self.c.setMinimumSize(QSize(60, 60))
        self.c.setMaximumSize(QSize(60, 60))
        self.c.setFont(font)
        self.c.setFocusPolicy(Qt.NoFocus)
        self.c.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.c)

        self.v = VKBKey(self.vkb_buttons)
        self.v.setObjectName(u"v")
        sizePolicy.setHeightForWidth(self.v.sizePolicy().hasHeightForWidth())
        self.v.setSizePolicy(sizePolicy)
        self.v.setMinimumSize(QSize(60, 60))
        self.v.setMaximumSize(QSize(60, 60))
        self.v.setFont(font)
        self.v.setFocusPolicy(Qt.NoFocus)
        self.v.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.v)

        self.b = VKBKey(self.vkb_buttons)
        self.b.setObjectName(u"b")
        sizePolicy.setHeightForWidth(self.b.sizePolicy().hasHeightForWidth())
        self.b.setSizePolicy(sizePolicy)
        self.b.setMinimumSize(QSize(60, 60))
        self.b.setMaximumSize(QSize(60, 60))
        self.b.setFont(font)
        self.b.setFocusPolicy(Qt.NoFocus)
        self.b.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.b)

        self.n = VKBKey(self.vkb_buttons)
        self.n.setObjectName(u"n")
        sizePolicy.setHeightForWidth(self.n.sizePolicy().hasHeightForWidth())
        self.n.setSizePolicy(sizePolicy)
        self.n.setMinimumSize(QSize(60, 60))
        self.n.setMaximumSize(QSize(60, 60))
        self.n.setFont(font)
        self.n.setFocusPolicy(Qt.NoFocus)
        self.n.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.n)

        self.m = VKBKey(self.vkb_buttons)
        self.m.setObjectName(u"m")
        sizePolicy.setHeightForWidth(self.m.sizePolicy().hasHeightForWidth())
        self.m.setSizePolicy(sizePolicy)
        self.m.setMinimumSize(QSize(60, 60))
        self.m.setMaximumSize(QSize(60, 60))
        self.m.setFont(font)
        self.m.setFocusPolicy(Qt.NoFocus)
        self.m.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.m)

        self.comma = VKBKey(self.vkb_buttons)
        self.comma.setObjectName(u"comma")
        sizePolicy.setHeightForWidth(self.comma.sizePolicy().hasHeightForWidth())
        self.comma.setSizePolicy(sizePolicy)
        self.comma.setMinimumSize(QSize(60, 60))
        self.comma.setMaximumSize(QSize(60, 60))
        self.comma.setFont(font)
        self.comma.setFocusPolicy(Qt.NoFocus)
        self.comma.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.comma)

        self.period = VKBKey(self.vkb_buttons)
        self.period.setObjectName(u"period")
        sizePolicy.setHeightForWidth(self.period.sizePolicy().hasHeightForWidth())
        self.period.setSizePolicy(sizePolicy)
        self.period.setMinimumSize(QSize(60, 60))
        self.period.setMaximumSize(QSize(60, 60))
        self.period.setFont(font)
        self.period.setFocusPolicy(Qt.NoFocus)
        self.period.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.period)

        self.frontslash = VKBKey(self.vkb_buttons)
        self.frontslash.setObjectName(u"frontslash")
        sizePolicy.setHeightForWidth(self.frontslash.sizePolicy().hasHeightForWidth())
        self.frontslash.setSizePolicy(sizePolicy)
        self.frontslash.setMinimumSize(QSize(60, 60))
        self.frontslash.setMaximumSize(QSize(60, 60))
        self.frontslash.setFont(font)
        self.frontslash.setFocusPolicy(Qt.NoFocus)
        self.frontslash.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.frontslash)

        self.pushButton_67 = VKBKey(self.vkb_buttons)
        self.pushButton_67.setObjectName(u"pushButton_67")
        sizePolicy1.setHeightForWidth(self.pushButton_67.sizePolicy().hasHeightForWidth())
        self.pushButton_67.setSizePolicy(sizePolicy1)
        self.pushButton_67.setMinimumSize(QSize(90, 60))
        self.pushButton_67.setMaximumSize(QSize(79, 60))
        self.pushButton_67.setFont(font)
        self.pushButton_67.setFocusPolicy(Qt.NoFocus)
        self.pushButton_67.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.pushButton_67)

        self.up_arrow = VKBKey(self.vkb_buttons)
        self.up_arrow.setObjectName(u"up_arrow")
        sizePolicy.setHeightForWidth(self.up_arrow.sizePolicy().hasHeightForWidth())
        self.up_arrow.setSizePolicy(sizePolicy)
        self.up_arrow.setMinimumSize(QSize(60, 60))
        self.up_arrow.setMaximumSize(QSize(60, 60))
        self.up_arrow.setFont(font2)
        self.up_arrow.setFocusPolicy(Qt.NoFocus)
        self.up_arrow.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u":/images/up_arrow.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.up_arrow.setIcon(icon)
        self.up_arrow.setIconSize(QSize(40, 40))

        self.horizontalLayout_5.addWidget(self.up_arrow)

        self.end = VKBKey(self.vkb_buttons)
        self.end.setObjectName(u"end")
        sizePolicy.setHeightForWidth(self.end.sizePolicy().hasHeightForWidth())
        self.end.setSizePolicy(sizePolicy)
        self.end.setMinimumSize(QSize(60, 60))
        self.end.setMaximumSize(QSize(60, 60))
        self.end.setFont(font1)
        self.end.setFocusPolicy(Qt.NoFocus)
        self.end.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.end)

        self.np0 = VKBKey(self.vkb_buttons)
        self.np0.setObjectName(u"np0")
        sizePolicy.setHeightForWidth(self.np0.sizePolicy().hasHeightForWidth())
        self.np0.setSizePolicy(sizePolicy)
        self.np0.setMinimumSize(QSize(60, 60))
        self.np0.setMaximumSize(QSize(60, 60))
        self.np0.setFont(font2)
        self.np0.setFocusPolicy(Qt.NoFocus)
        self.np0.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.np0)

        self.pushButton_11 = VKBKey(self.vkb_buttons)
        self.pushButton_11.setObjectName(u"pushButton_11")
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QSize(60, 60))
        self.pushButton_11.setMaximumSize(QSize(60, 60))
        self.pushButton_11.setFont(font)
        self.pushButton_11.setFocusPolicy(Qt.NoFocus)
        self.pushButton_11.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.pushButton_11)

        self.backspace = VKBKey(self.vkb_buttons)
        self.backspace.setObjectName(u"backspace")
        sizePolicy.setHeightForWidth(self.backspace.sizePolicy().hasHeightForWidth())
        self.backspace.setSizePolicy(sizePolicy)
        self.backspace.setMinimumSize(QSize(60, 60))
        self.backspace.setMaximumSize(QSize(60, 60))
        self.backspace.setFont(font)
        self.backspace.setFocusPolicy(Qt.NoFocus)
        self.backspace.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/images/backspace.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.backspace.setIcon(icon1)
        self.backspace.setIconSize(QSize(45, 45))

        self.horizontalLayout_5.addWidget(self.backspace)

        self.add = VKBKey(self.vkb_buttons)
        self.add.setObjectName(u"add")
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setMinimumSize(QSize(60, 60))
        self.add.setMaximumSize(QSize(60, 60))
        self.add.setFont(font2)
        self.add.setFocusPolicy(Qt.NoFocus)
        self.add.setStyleSheet(u"")

        self.horizontalLayout_5.addWidget(self.add)


        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.CTRL_2 = VKBKey(self.vkb_buttons)
        self.CTRL_2.setObjectName(u"CTRL_2")
        sizePolicy.setHeightForWidth(self.CTRL_2.sizePolicy().hasHeightForWidth())
        self.CTRL_2.setSizePolicy(sizePolicy)
        self.CTRL_2.setMinimumSize(QSize(70, 60))
        self.CTRL_2.setMaximumSize(QSize(70, 60))
        self.CTRL_2.setFont(font)
        self.CTRL_2.setFocusPolicy(Qt.NoFocus)
        self.CTRL_2.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.CTRL_2)

        self.ALT = VKBKey(self.vkb_buttons)
        self.ALT.setObjectName(u"ALT")
        sizePolicy.setHeightForWidth(self.ALT.sizePolicy().hasHeightForWidth())
        self.ALT.setSizePolicy(sizePolicy)
        self.ALT.setMinimumSize(QSize(70, 60))
        self.ALT.setMaximumSize(QSize(70, 60))
        self.ALT.setFont(font)
        self.ALT.setFocusPolicy(Qt.NoFocus)
        self.ALT.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.ALT)

        self.space = VKBKey(self.vkb_buttons)
        self.space.setObjectName(u"space")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(1)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.space.sizePolicy().hasHeightForWidth())
        self.space.setSizePolicy(sizePolicy2)
        self.space.setMinimumSize(QSize(0, 60))
        self.space.setMaximumSize(QSize(16777215, 60))
        self.space.setFont(font2)
        self.space.setFocusPolicy(Qt.NoFocus)
        self.space.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.space)

        self.FN = VKBKey(self.vkb_buttons)
        self.FN.setObjectName(u"FN")
        sizePolicy.setHeightForWidth(self.FN.sizePolicy().hasHeightForWidth())
        self.FN.setSizePolicy(sizePolicy)
        self.FN.setMinimumSize(QSize(70, 60))
        self.FN.setMaximumSize(QSize(70, 60))
        self.FN.setFont(font)
        self.FN.setFocusPolicy(Qt.NoFocus)
        self.FN.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.FN)

        self.CTRL = VKBKey(self.vkb_buttons)
        self.CTRL.setObjectName(u"CTRL")
        sizePolicy.setHeightForWidth(self.CTRL.sizePolicy().hasHeightForWidth())
        self.CTRL.setSizePolicy(sizePolicy)
        self.CTRL.setMinimumSize(QSize(70, 60))
        self.CTRL.setMaximumSize(QSize(70, 60))
        self.CTRL.setFont(font)
        self.CTRL.setFocusPolicy(Qt.NoFocus)
        self.CTRL.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.CTRL)

        self.left_arrow = VKBKey(self.vkb_buttons)
        self.left_arrow.setObjectName(u"left_arrow")
        sizePolicy.setHeightForWidth(self.left_arrow.sizePolicy().hasHeightForWidth())
        self.left_arrow.setSizePolicy(sizePolicy)
        self.left_arrow.setMinimumSize(QSize(60, 60))
        self.left_arrow.setMaximumSize(QSize(60, 60))
        self.left_arrow.setFont(font2)
        self.left_arrow.setFocusPolicy(Qt.NoFocus)
        self.left_arrow.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u":/images/left_arrow.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.left_arrow.setIcon(icon2)
        self.left_arrow.setIconSize(QSize(40, 40))

        self.horizontalLayout_6.addWidget(self.left_arrow)

        self.down_arrow = VKBKey(self.vkb_buttons)
        self.down_arrow.setObjectName(u"down_arrow")
        sizePolicy.setHeightForWidth(self.down_arrow.sizePolicy().hasHeightForWidth())
        self.down_arrow.setSizePolicy(sizePolicy)
        self.down_arrow.setMinimumSize(QSize(60, 60))
        self.down_arrow.setMaximumSize(QSize(60, 60))
        self.down_arrow.setFont(font2)
        self.down_arrow.setFocusPolicy(Qt.NoFocus)
        self.down_arrow.setStyleSheet(u"")
        icon3 = QIcon()
        icon3.addFile(u":/images/down_arrow.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.down_arrow.setIcon(icon3)
        self.down_arrow.setIconSize(QSize(40, 40))

        self.horizontalLayout_6.addWidget(self.down_arrow)

        self.right_arrow = VKBKey(self.vkb_buttons)
        self.right_arrow.setObjectName(u"right_arrow")
        sizePolicy.setHeightForWidth(self.right_arrow.sizePolicy().hasHeightForWidth())
        self.right_arrow.setSizePolicy(sizePolicy)
        self.right_arrow.setMinimumSize(QSize(60, 60))
        self.right_arrow.setMaximumSize(QSize(60, 60))
        self.right_arrow.setFont(font2)
        self.right_arrow.setFocusPolicy(Qt.NoFocus)
        self.right_arrow.setStyleSheet(u"")
        icon4 = QIcon()
        icon4.addFile(u":/images/right_arrow.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.right_arrow.setIcon(icon4)
        self.right_arrow.setIconSize(QSize(40, 40))

        self.horizontalLayout_6.addWidget(self.right_arrow)

        self.esc = VKBKey(self.vkb_buttons)
        self.esc.setObjectName(u"esc")
        sizePolicy1.setHeightForWidth(self.esc.sizePolicy().hasHeightForWidth())
        self.esc.setSizePolicy(sizePolicy1)
        self.esc.setMinimumSize(QSize(83, 60))
        self.esc.setMaximumSize(QSize(83, 60))
        self.esc.setSizeIncrement(QSize(0, 0))
        self.esc.setBaseSize(QSize(0, 0))
        self.esc.setFont(font)
        self.esc.setFocusPolicy(Qt.NoFocus)
        self.esc.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.esc)

        self.pushButton_20 = VKBKey(self.vkb_buttons)
        self.pushButton_20.setObjectName(u"pushButton_20")
        sizePolicy1.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy1)
        self.pushButton_20.setMinimumSize(QSize(83, 60))
        self.pushButton_20.setMaximumSize(QSize(83, 60))
        self.pushButton_20.setFont(font)
        self.pushButton_20.setFocusPolicy(Qt.NoFocus)

        self.horizontalLayout_6.addWidget(self.pushButton_20)

        self.enter = VKBKey(self.vkb_buttons)
        self.enter.setObjectName(u"enter")
        sizePolicy1.setHeightForWidth(self.enter.sizePolicy().hasHeightForWidth())
        self.enter.setSizePolicy(sizePolicy1)
        self.enter.setMinimumSize(QSize(83, 60))
        self.enter.setMaximumSize(QSize(83, 60))
        self.enter.setFont(font)
        self.enter.setFocusPolicy(Qt.NoFocus)
        self.enter.setStyleSheet(u"")

        self.horizontalLayout_6.addWidget(self.enter)


        self.verticalLayout_2.addLayout(self.horizontalLayout_6)


        self.verticalLayout.addWidget(self.vkb_buttons)


        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.pushButton_87.setText(QCoreApplication.translate("Dialog", u"`", None))
        self.mk1.setText(QCoreApplication.translate("Dialog", u"1", None))
        self.mk2.setText(QCoreApplication.translate("Dialog", u"2", None))
        self.mk3.setText(QCoreApplication.translate("Dialog", u"3", None))
        self.mk4.setText(QCoreApplication.translate("Dialog", u"4", None))
        self.mk5.setText(QCoreApplication.translate("Dialog", u"5", None))
        self.mk6.setText(QCoreApplication.translate("Dialog", u"6", None))
        self.mk7.setText(QCoreApplication.translate("Dialog", u"7", None))
        self.mk8.setText(QCoreApplication.translate("Dialog", u"8", None))
        self.mk9.setText(QCoreApplication.translate("Dialog", u"9", None))
        self.mk0.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.dash.setText(QCoreApplication.translate("Dialog", u"-", None))
        self.equals.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.backspace_2.setText(QCoreApplication.translate("Dialog", u"BACK", None))
        self.backspace_2.setProperty(u"key", QCoreApplication.translate("Dialog", u"Backspace", None))
        self.insert.setText(QCoreApplication.translate("Dialog", u"INSERT", None))
        self.insert.setProperty(u"key", QCoreApplication.translate("Dialog", u"Ins", None))
        self.insert.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"blue_white", None))
        self.np7.setText(QCoreApplication.translate("Dialog", u"7", None))
        self.np7.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.np8.setText(QCoreApplication.translate("Dialog", u"8", None))
        self.np8.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.np9.setText(QCoreApplication.translate("Dialog", u"9", None))
        self.np9.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.divide.setText(QCoreApplication.translate("Dialog", u"\u00f7", None))
        self.divide.setProperty(u"key", QCoreApplication.translate("Dialog", u"/", None))
        self.divide.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"symbols", None))
        self.TAB.setText(QCoreApplication.translate("Dialog", u"TAB", None))
        self.q.setStyleSheet("")
        self.q.setText(QCoreApplication.translate("Dialog", u"Q", None))
        self.q.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.w.setText(QCoreApplication.translate("Dialog", u"W", None))
        self.w.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.e.setText(QCoreApplication.translate("Dialog", u"E", None))
        self.e.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.r.setText(QCoreApplication.translate("Dialog", u"R", None))
        self.r.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.t.setText(QCoreApplication.translate("Dialog", u"T", None))
        self.t.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_blue", None))
        self.y.setText(QCoreApplication.translate("Dialog", u"Y", None))
        self.y.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_black", None))
        self.u.setText(QCoreApplication.translate("Dialog", u"U", None))
        self.u.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.i.setText(QCoreApplication.translate("Dialog", u"I", None))
        self.i.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.o.setText(QCoreApplication.translate("Dialog", u"O", None))
        self.o.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.p.setText(QCoreApplication.translate("Dialog", u"P", None))
        self.p.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.left_bracket.setText(QCoreApplication.translate("Dialog", u"[", None))
        self.right_bracket.setText(QCoreApplication.translate("Dialog", u"]", None))
        self.backslash.setText(QCoreApplication.translate("Dialog", u"\\", None))
        self.dlt.setText(QCoreApplication.translate("Dialog", u"DEL", None))
        self.dlt.setProperty(u"key", QCoreApplication.translate("Dialog", u"Del", None))
        self.dlt.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"blue_white", None))
        self.np4.setText(QCoreApplication.translate("Dialog", u"4", None))
        self.np4.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.np5.setText(QCoreApplication.translate("Dialog", u"5", None))
        self.np5.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.np6.setText(QCoreApplication.translate("Dialog", u"6", None))
        self.np6.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.multiply.setText(QCoreApplication.translate("Dialog", u"\u00d7", None))
        self.multiply.setProperty(u"key", QCoreApplication.translate("Dialog", u"*", None))
        self.multiply.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"symbols", None))
        self.CAPS.setText(QCoreApplication.translate("Dialog", u"CAPS", None))
        self.a.setText(QCoreApplication.translate("Dialog", u"A", None))
        self.a.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.s.setText(QCoreApplication.translate("Dialog", u"S", None))
        self.s.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_blue", None))
        self.d.setText(QCoreApplication.translate("Dialog", u"D", None))
        self.d.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.f.setText(QCoreApplication.translate("Dialog", u"F", None))
        self.f.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_blue", None))
        self.g.setText(QCoreApplication.translate("Dialog", u"G", None))
        self.g.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_blue", None))
        self.h.setText(QCoreApplication.translate("Dialog", u"H", None))
        self.h.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.j.setText(QCoreApplication.translate("Dialog", u"J", None))
        self.j.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.k.setText(QCoreApplication.translate("Dialog", u"K", None))
        self.k.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.l.setText(QCoreApplication.translate("Dialog", u"L", None))
        self.l.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.semicolon.setText(QCoreApplication.translate("Dialog", u";", None))
        self.apostraphe.setText(QCoreApplication.translate("Dialog", u"'", None))
        self.enter_2.setText(QCoreApplication.translate("Dialog", u"ENTER", None))
        self.enter_2.setProperty(u"key", QCoreApplication.translate("Dialog", u"Return", None))
        self.home.setText(QCoreApplication.translate("Dialog", u"HOME", None))
        self.home.setProperty(u"key", QCoreApplication.translate("Dialog", u"Home", None))
        self.home.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"blue_white", None))
        self.np1.setText(QCoreApplication.translate("Dialog", u"1", None))
        self.np1.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.np2.setText(QCoreApplication.translate("Dialog", u"2", None))
        self.np2.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.np3.setText(QCoreApplication.translate("Dialog", u"3", None))
        self.np3.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.subtract.setText(QCoreApplication.translate("Dialog", u"\u2212", None))
        self.subtract.setProperty(u"key", QCoreApplication.translate("Dialog", u"-", None))
        self.subtract.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"symbols", None))
        self.vbkmodifierkey.setText(QCoreApplication.translate("Dialog", u"SHIFT", None))
        self.z.setText(QCoreApplication.translate("Dialog", u"Z", None))
        self.z.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_black", None))
        self.x.setText(QCoreApplication.translate("Dialog", u"X", None))
        self.x.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_black", None))
        self.c.setText(QCoreApplication.translate("Dialog", u"C", None))
        self.c.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.v.setText(QCoreApplication.translate("Dialog", u"V", None))
        self.v.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.b.setText(QCoreApplication.translate("Dialog", u"B", None))
        self.b.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.n.setText(QCoreApplication.translate("Dialog", u"N", None))
        self.n.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.m.setText(QCoreApplication.translate("Dialog", u"M", None))
        self.m.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_blue", None))
        self.comma.setText(QCoreApplication.translate("Dialog", u",", None))
        self.period.setText(QCoreApplication.translate("Dialog", u".", None))
        self.frontslash.setText(QCoreApplication.translate("Dialog", u"/", None))
        self.pushButton_67.setText(QCoreApplication.translate("Dialog", u"shift", None))
        self.up_arrow.setText("")
        self.up_arrow.setProperty(u"key", QCoreApplication.translate("Dialog", u"Up", None))
        self.up_arrow.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.end.setText(QCoreApplication.translate("Dialog", u"END", None))
        self.end.setProperty(u"key", QCoreApplication.translate("Dialog", u"End", None))
        self.end.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"blue_white", None))
        self.np0.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.np0.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.pushButton_11.setText(QCoreApplication.translate("Dialog", u".", None))
        self.backspace.setText("")
        self.add.setText(QCoreApplication.translate("Dialog", u"+", None))
        self.add.setProperty(u"key", QCoreApplication.translate("Dialog", u"+", None))
        self.add.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"symbols", None))
        self.CTRL_2.setText(QCoreApplication.translate("Dialog", u"CTRL", None))
        self.ALT.setText(QCoreApplication.translate("Dialog", u"ALT", None))
        self.space.setText("")
        self.space.setProperty(u"key", QCoreApplication.translate("Dialog", u"Space", None))
        self.space.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.FN.setText(QCoreApplication.translate("Dialog", u"FN", None))
        self.CTRL.setText(QCoreApplication.translate("Dialog", u"CTRL", None))
        self.left_arrow.setText("")
        self.left_arrow.setProperty(u"key", QCoreApplication.translate("Dialog", u"Left", None))
        self.left_arrow.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.down_arrow.setText("")
        self.down_arrow.setProperty(u"key", QCoreApplication.translate("Dialog", u"Down", None))
        self.down_arrow.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.right_arrow.setText("")
        self.right_arrow.setProperty(u"key", QCoreApplication.translate("Dialog", u"Right", None))
        self.right_arrow.setProperty(u"buttonColorGroup", QCoreApplication.translate("Dialog", u"light_white", None))
        self.esc.setText(QCoreApplication.translate("Dialog", u"ESC", None))
        self.esc.setProperty(u"key", QCoreApplication.translate("Dialog", u"Esc", None))
        self.pushButton_20.setStyleSheet("")
        self.pushButton_20.setText(QCoreApplication.translate("Dialog", u"in/mm", None))
        self.enter.setText(QCoreApplication.translate("Dialog", u"ENTER", None))
        self.enter.setProperty(u"key", QCoreApplication.translate("Dialog", u"Return", None))
    # retranslateUi

